26 Feb Assignment 25

Both Questions and Answers are written:---

Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [7]:
# Ans: Yes, both have different datatypes

In [1]:
import numpy as np

In [2]:
list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_)

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [46]:
# Ans:2

In [16]:
type(list_[0])
type(list_[1])
type(list_[2])
type(list_[3])
type(list_[4])

str

In [18]:
type(array_list[0])
type(array_list[1])
type(array_list[2])
type(array_list[3])
type(array_list[4])

numpy.str_

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Ans:4- Yes, there is difference of datatype in both the variables.

In [19]:
array_list = np.array(object = list_, dtype = int)

In [23]:
type(list_[0])
type(list_[1])
type(list_[2])
type(list_[3])
type(list_[4])

str

In [24]:
type(array_list[0])
type(array_list[1])
type(array_list[2])
type(array_list[3])
type(array_list[4])

numpy.int64

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [26]:
num_array = np.array(object = num_list)

In [37]:
# Ans:4
# (i)
num_array.shape

(2, 3)

In [36]:
# (ii)
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [30]:
# Ans:5

marray = np.zeros((3,3))

In [31]:
marray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
marray.size

9

In [33]:
marray.shape

(3, 3)

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [45]:
# Ans:6

ar = np.ones(5)

In [41]:
ar

array([1., 1., 1., 1., 1.])

In [44]:
np.diag(ar)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])